---
title: "Overview"
output: html_document
---

Creating Ecological Metadata Language (EML) metadata for NPS data packages is a two-step process.

The first step is to generate an EML formatted .xml file. There are a number of tools for generating this initial file. This repo contains an R script, instructions, and an example of how to use EMLassemblyline to generate an initial EML metadata file while taking into consideration NPS data package specifications and requirements for uploading to DataStore.

No matter the method of generating the initial EML file, the second step is to add NPS-specific information to the EML metadata (for instance, the data pacakge DOI, links to the DRR, information about CUI, producing units and unit connections). Currently, the only tool for adding NPS-specific metadata is the [R/EMLeditor](https://github.com/nationalparkservice/EMLeditor) package. Editing EML by hand is not advised.

This is an early version of this template. Please request enhancements and bug fixes through [Issues](https://github.com/nationalparkservice/NPS_EML_Script/issues).

You can also directly access the [source files](https://github.com/nationalparkservice/NPS_EML_Script) for this webpage and the entire repo, as well as download the entire repo as [zip file](https://github.com/nationalparkservice/NPS_EML_Script/zipball/master).

# Quickstart:

  To jump right into creating EML, check out our [quickstart quide](README.html)

# Detailed guide:

  * [Prerequisites for EML metadata creation](prereqs.html)
  
    * Download the NPS [EML Creation script and associated folders](https://github.com/nationalparkservice/NPS_EML_Script/zipball/master)
  
    * This includes an [NPS EML Script with example EML creation](https://github.com/nationalparkservice/NPS_EML_Script/blob/main/EML_Creation_Script.R) that you can edit/modify to generate your own EML
  
      * Two .csv data file inputs for the example:
    
        * [qry_Export_AA_Points.csv](https://github.com/nationalparkservice/NPS_EML_Script/blob/main/Example_files/qry_Export_AA_Points.csv)
    
        * [qry_Export_AA_VegetationDetails.csv](https://github.com/nationalparkservice/NPS_EML_Script/blob/main/Example_files/qry_Export_AA_VegetationDetail.csv)
        
      * A series of example .txt files that were generated using EMLassemblyline functions. These example files have already been edited to make the example EML files  
    
      * [Example EML metadata file](https://github.com/nationalparkservice/NPS_EML_Script/blob/main/Example_files/TEST_EVER_AA_metadata.xml)
    
  * A [step-by-step guide](stepbystep.html) for using the NPS EML Creation Script
  
  * References:
  
    * [Guidance](edit_tmplts.html) on editing metadata templates (.txt files)

    * [Functions for generating metadata templates](create_tmplts.html)
  
    * [A function to create EML metadata](create_eml.html)

# Next Steps:

The example EML file [EVER_AA_metadata.xml](https://github.com/nationalparkservice/NPS_EML_Script/EVER_AA_metadata.xml) as well as the EML you have created are not the final step in NPS EML creation. At this point you have filled in much of the important scientific information in the metadata. However, to fully utilize DataStore's new capabilities and to make sure your data are easily discoverable and reusable, you still need to edit the EML file to provide NPS-specific information (e.g. publisher, unit connections, DOIs, etc). Currently, the only tool available is [R/EMLeditor](https://github.com/nationalparkservice/EMLeditor). Manually editing your metadata by hand is not recommended.

For a detailed workflow on how to use EMLeditor to generate the highest quality metadata, please see (**under development**)

# Additional Documentation
1.    The original [EDI guidelines](https://ediorg.github.io/EMLassemblyline/articles/edit_tmplts.html) for creating EML.
2.    Additional [information about EML](https://eml.ecoinformatics.org/).
3.    The official [EML schema](https://eml.ecoinformatics.org/schema/index.html).

# Acknowledgements
EMLassemblyline and much of the excellent original documentation was developed by the Environmental Data Initiative. We have modified and annotated that documentation to make it more relevant to NPS.