---
title: "NPS EML Scripting"
description: |
  Resources and Guides for using EMLassemblyline to create EML for National Park Service data packages
site: distill::distill_website
output:
  distill::distill_article:
    toc: true
    toc_depth: 6
    toc_float: true
    css: toc-styles.css
    self_contained: false
---

---
output: github_document

---

# Comprehensive guide:

  * [Prerequisites for EML metadata creation](prereqs.html)
  
    * Download the NPS [EML Creation script and associated folders](https://github.com/nationalparkservice/NPS_EML_Script/zipball/master)
  
    * This includes an [NPS EML Script with example EML creation](https://github.com/nationalparkservice/NPS_EML_Script/blob/main/EML_Creation_Script.R) that you can edit/modify to generate your own EML
  
      * Two .csv data file inputs for the example:
    
        * [qry_Export_AA_Points.csv](https://github.com/nationalparkservice/NPS_EML_Script/blob/main/Example_files/qry_Export_AA_Points.csv)
    
        * [qry_Export_AA_VegetationDetails.csv](https://github.com/nationalparkservice/NPS_EML_Script/blob/main/Example_files/qry_Export_AA_VegetationDetail.csv)
        
      * A series of example .txt files that were generated using EMLassemblyline functions. These example files have already been edited to make the example EML files  
    
      * [Example EML metadata file](https://github.com/nationalparkservice/NPS_EML_Script/blob/main/Example_files/TEST_EVER_AA_metadata.xml)
    
  * A [step-by-step guide](stepbystep.html) for using the NPS EML Creation Script
  
  * References:
  
    * [Guidance](edit_tmplts.html) on editing metadata templates (.txt files)

    * [Functions for generating metadata templates](create_tmplts.html)
  
    * [A function to create EML metadata](create_eml.html)

# Next Steps:

The example EML file [EVER_AA_metadata.xml](https://github.com/nationalparkservice/NPS_EML_Script/EVER_AA_metadata.xml) as well as the EML you have created are not the final step in NPS EML creation. At this point you have filled in much of the important scientific information in the metadata. However, to fully utilize DataStore's new capabilities and to make sure your data are easily discoverable and reusable, you still need to edit the EML file to provide NPS-specific information (e.g. publisher, unit connections, DOIs, etc). Currently, the only tool available is [R/EMLeditor](https://github.com/nationalparkservice/EMLeditor). Manually editing your metadata by hand is not recommended.

For a detailed workflow on how to use EMLeditor to generate the highest quality metadata, please see (**under development**)

# Additional Documentation
1.    The original [EDI guidelines](https://ediorg.github.io/EMLassemblyline/articles/edit_tmplts.html) for creating EML.
2.    Additional [information about EML](https://eml.ecoinformatics.org/).
3.    The official [EML schema](https://eml.ecoinformatics.org/schema/index.html).

# Acknowledgements
EMLassemblyline and much of the excellent original documentation was developed by the Environmental Data Initiative. We have modified and annotated that documentation to make it more relevant to NPS.