---
title: "NPS EML Scripting"
description: |
  Resources and Guides for using EMLassemblyline to create EML for National Park Service data packages
site: distill::distill_website
output:
  distill::distill_article:
    toc: true
    toc_depth: 6
    toc_float: true
    self_contained: false
---

---
output: github_document
---

# Quickstart

### Prior to generating EML you will need the following:

1) Data: A set of fully QA/QC'd data files in .csv format using UTF-8 encoding. 

2) Internet access: for downloading software and packages. A strong internet connection is necessary, particularly if you have taxonomic information as EMLassemblyline will use scientific names to reach out to ITIS and/or GBIF to populate taxonomic coverage fields from Kingdom down to species (and beyond).

3) Software: R (and probably RStudio) installed on your computer. These are both available in Software Center. See the [R Advisory Group's website](https://doimspp.sharepoint.com/sites/nps-nrss-imdiv/SitePages/R-Adv.aspx) for more information. You will also need to install the R package [EMLassemblyline](https://github.com/EDIorg/EMLassemblyline) from GitHub as well as some other packages from CRAN. These can all be installed at once using the R package [NPSdataverse](https://nationalparkservice.github.io/NPSdataverse/):

```{r install, eval=FALSE}
#install packages:
install.packages(c("devtools", "lubridate", "tidyverse"))
library(devtools)

#the NPSdataverse includes EMLassemblyline and several other useful packages:
install_github("nationalparkservice/NPSdataverse")

library("lubridate", "tidyverse", "NPSdataverse")S
```

4) Access to MS Excel (or any spreadsheet type programs) and Notepad (or any text editor). These will facilitate editing tab-delimited files. 

### Download the Script 

A stand-alone version of the NPS [EML Creation script](https://downgit.github.io/#/home?url=https://github.com/nationalparkservice/NPS_EML_Script/blob/main/EML_Creation_Script.R) is available for download. You don't have to download the entire repository to make EML.

### Generate EML

1) Edit the *EML_Creation_Script.R* file as necessary and run each line or set of code (except the `make_eml` function). 

2) Edit the auto-generated .txt files using a text editor or spreadsheet application as necessary. For details, look at the NPS [template editing guideline](edit_tmplts.html). 

3) Run the `make_eml` function (this could take a little while - particularly if you have a lot of taxonomic data).

4) Be sure to read and address any Issues or Warnings after running the `make_eml` function.

### Next steps

The EML you have created is not the final step in NPS EML creation. To fully utilize DataStore's new capabilities and to make sure your data are easily discoverable and reusable, you still need to edit the EML file to provide NPS-specific information (e.g. publisher, unit connections, DOIs, etc). 

Currently, the only tool available to add NPS-specific information to EML is [R/EMLeditor](https://nationalparkservice.github.io/EMLeditor/). Manually editing your metadata by hand is not recommended.

# Additional documentation

1) The [Comprehensive guide](comprehensive_guide.html) to using the NPS EML creation script.
2) The original [EDI guidelines](https://ediorg.github.io/EMLassemblyline/articles/edit_tmplts.html) for creating EML.

# Acknowledgements

EMLassemblyline and much of the excellent original documentation was developed by the Environmental Data Initiative. We have modified and annotated that documentation to make it more relevant to NPS.
